"""Added Oauth accounts table

Revision ID: 4042e07f7f02
Revises: e3ebdad8a5a4
Create Date: 2026-08-04 11:53:45.424550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4042e07f7f02'
down_revision: Union[str, Sequence[str], None] = 'e3ebdad8a5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
