"""Added Oauth accounts table

Revision ID: e3ebdad8a5a4
Revises: 37996b3dc9c7
Create Date: 2026-08-04 11:49:48.495429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ebdad8a5a4'
down_revision: Union[str, Sequence[str], None] = '37996b3dc9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
